spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: asddsa123472@gmail.com
    password: koreait1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3308/facebook
    username: root
    password: koreait
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: D:/springImg

  ## 소셜로그인
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 897062476820-0ldppkcuskompdiu5j6j58non6f9p7cm.apps.googleusercontent.com
            client-secret: Y-RixXJTJ9RxfmDlzTo0P7Yz

            scope:
              - profile
              - email
          facebook:
            client-id: 208022541244642
            client-secret: a663bcad3a2400fa20b51cfa708d2774
          kakao:
            authorization-grant-type: authorization_code
            client-id: 408f05189f205c2a3ce900fe55bf3495 # rest API 키
            client-secret: 740zZiOCzHGNcDz6Mv3jPYzjIC6niyIK # client secret 코드
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
            client-authentication-method: POST
            client-name: Kakao
          naver:
            authorization-grant-type: authorization_code
            client-id: 8rVjpA43vq0yo13vhGrW
            client-secret: YgPmGF5o21
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: name, profile_image
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties
            # JSON 형태에서 "properties"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            # JSON 형태에서 "response"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.facebook

#톰캣 포트 변경
server:
  port: 8090